# If you installed yabai or aerospace without using Homebrew,
# manually set the path to the binary. For example:
#
# yabai.path = "/run/current-system/sw/bin/yabai"
# aerospace.path = ...

theme = "system" # system, light, dark

[widgets]
displayed = [ # widgets on menu bar
  "default.spaces",
  "spacer",
  "default.nowplaying",
  # "default.network",
  "default.battery",
  # "divider",
  # { "default.time" = { time-zone = "America/Los_Angeles", format = "E d, hh:mm" } },
  # "default.time",
]

[widgets.default.spaces]
space.show-key = true        # show space number (or character, if you use AeroSpace)
window.show-title = true
window.title.max-length = 50

# A list of applications that will always be displayed by application name.
# Other applications will show the window title if there is more than one window.
window.title.always-display-app-name-for = ["Whatsapp", "Dia", "Spotify"]

[widgets.default.nowplaying.popup]
view-variant = "vertical"

[widgets.default.battery]
show-percentage = true
warning-level = 30
critical-level = 10

[widgets.default.time]
format = "E d, J:mm"
calendar.format = "J:mm"


[widgets.default.time.popup]
view-variant = "box"


### EXPERIMENTAL, WILL BE REPLACED BY STYLE API IN THE FUTURE

[experimental.foreground] # settings for menu bar
height = 28            # available values: default (55.0), menu-bar (height like system menu bar), <float> (e.g., 40, 33.5)
horizontal-padding = 8 # padding on the left and right corners
spacing = 8            # spacing between widgets
